"""Bootstrap extension-owned dependencies and managed launch setup."""

from __future__ import annotations

import importlib.metadata
import re
from pathlib import Path
from textwrap import dedent
from typing import Optional

from packaging.version import parse as parse_version

import launch

REPO_ROOT = Path(__file__).resolve().parent
REQUIREMENTS_FILE = REPO_ROOT / "requirements.txt"
INSTALLER_NAME = "sd-forge-rouwei-gemma-adapter"
REQUIRED_TRANSFORMERS_VERSION = "4.53.1"
MANAGED_LAUNCHER_NAME = "webui-user-gemma-adapter.bat"
USER_LAUNCHER_NAME = "webui-user.bat"
HOST_LAUNCHER_NAME = "webui.bat"
MANAGED_LAUNCHER_COMMENT = (
    "Managed by sd-forge-rouwei-gemma-adapter. Regenerated by install.py."
)


def get_installed_version(package_name: str) -> Optional[str]:
    """Return the installed version for one package name if it exists."""

    try:
        return importlib.metadata.version(package_name)
    except importlib.metadata.PackageNotFoundError:
        return None


def extract_base_package(requirement: str) -> str:
    """Extract the import/distribution name from one requirement string."""

    if "@" in requirement:
        return requirement.split("@", 1)[0].strip()
    if "==" in requirement:
        return requirement.split("==", 1)[0].strip()
    if ">=" in requirement:
        return requirement.split(">=", 1)[0].strip()
    return requirement.strip()


def should_upgrade_package(
    installed_version: str | None, required_version: str
) -> bool:
    """Return whether one installed package version is below the requirement."""

    if installed_version is None:
        return True
    return parse_version(installed_version) < parse_version(required_version)


def install_requirements(requirements_file: Path) -> None:
    """Install or upgrade extension-owned requirements when needed."""

    for raw_line in requirements_file.read_text(encoding="utf-8").splitlines():
        requirement = raw_line.split("#", 1)[0].strip()
        if not requirement:
            continue

        try:
            if "==" in requirement:
                package_name, expected_version = [
                    part.strip() for part in requirement.split("==", 1)
                ]
                installed_version = get_installed_version(package_name)
                if installed_version != expected_version:
                    launch.run_pip(
                        f'install -U "{requirement}"',
                        f"{INSTALLER_NAME} requirement: changing {package_name} from {installed_version} to {expected_version}",
                    )
            elif ">=" in requirement:
                package_name, minimum_version = [
                    part.strip() for part in requirement.split(">=", 1)
                ]
                installed_version = get_installed_version(package_name)
                if should_upgrade_package(installed_version, minimum_version):
                    launch.run_pip(
                        f'install -U "{requirement}"',
                        f"{INSTALLER_NAME} requirement: upgrading {package_name} from {installed_version} to at least {minimum_version}",
                    )
            elif not launch.is_installed(extract_base_package(requirement)):
                launch.run_pip(
                    f'install "{requirement}"',
                    f"{INSTALLER_NAME} requirement: {requirement}",
                )
        except Exception as exc:
            print(f"{INSTALLER_NAME}: failed to install {requirement}: {exc}")


def ensure_required_transformers_version() -> bool:
    """Install or upgrade host transformers to the required version."""

    installed_version = get_installed_version("transformers")
    if not should_upgrade_package(installed_version, REQUIRED_TRANSFORMERS_VERSION):
        return False

    launch.run_pip(
        f'install -U "transformers=={REQUIRED_TRANSFORMERS_VERSION}"',
        f"{INSTALLER_NAME} runtime: upgrading transformers from {installed_version} to {REQUIRED_TRANSFORMERS_VERSION}",
    )
    return True


def resolve_reforge_root(repo_root: Path = REPO_ROOT) -> Path:
    """Return the host ReForge root derived from the extension repo path."""

    reforge_root = repo_root.parent.parent
    host_launcher = reforge_root / HOST_LAUNCHER_NAME
    if not host_launcher.is_file():
        raise RuntimeError(
            f"{INSTALLER_NAME}: could not resolve ReForge root from {repo_root}."
        )
    return reforge_root


def get_user_launcher_path(reforge_root: Path) -> Path:
    """Return the host user-launcher path."""

    return reforge_root / USER_LAUNCHER_NAME


def get_host_launcher_path(reforge_root: Path) -> Path:
    """Return the host webui launcher path."""

    return reforge_root / HOST_LAUNCHER_NAME


def get_managed_launcher_path(reforge_root: Path) -> Path:
    """Return the managed Gemma launcher path."""

    return reforge_root / MANAGED_LAUNCHER_NAME


def extract_batch_variable(contents: str, variable_name: str) -> str:
    """Return the value assigned to one `set VAR=` batch variable."""

    pattern = re.compile(
        rf"(?im)^\s*set\s+{re.escape(variable_name)}=(.*)$",
    )
    match = pattern.search(contents)
    if match is None:
        return ""
    return match.group(1).strip()


def read_user_launcher_settings(user_launcher_path: Path) -> dict[str, str]:
    """Read selected batch variables from `webui-user.bat`."""

    settings = {
        "PYTHON": "",
        "GIT": "",
        "VENV_DIR": "",
        "COMMANDLINE_ARGS": "",
    }
    if not user_launcher_path.is_file():
        return settings

    contents = user_launcher_path.read_text(encoding="utf-8")
    for variable_name in settings:
        settings[variable_name] = extract_batch_variable(contents, variable_name)
    return settings


def merge_commandline_args(commandline_args: str) -> str:
    """Return one launch-args string with `--skip-install` present exactly once."""

    cleaned = commandline_args.strip()
    if re.search(r"(^|\s)--skip-install(\s|$)", cleaned):
        return cleaned
    if not cleaned:
        return "--skip-install"
    return f"{cleaned} --skip-install"


def render_managed_launcher(required_transformers_version: str) -> str:
    """Render the extension-owned managed launcher batch script."""

    return dedent(
        f"""\
        @echo off
        setlocal

        rem {MANAGED_LAUNCHER_COMMENT}
        set "REFORGE_ROOT=%~dp0"
        set "USER_LAUNCHER=%REFORGE_ROOT%{USER_LAUNCHER_NAME}"
        set "WEBUI_BAT=%REFORGE_ROOT%{HOST_LAUNCHER_NAME}"

        for /f "usebackq tokens=1,* delims==" %%A in (`powershell -NoProfile -ExecutionPolicy Bypass -Command "$settings = @{{ 'PYTHON' = ''; 'GIT' = ''; 'VENV_DIR' = ''; 'COMMANDLINE_ARGS' = '' }}; $path = $env:USER_LAUNCHER; if (Test-Path -LiteralPath $path) {{ foreach ($raw in Get-Content -LiteralPath $path) {{ if ($raw -match '^(?i)\\s*set\\s+(PYTHON|GIT|VENV_DIR|COMMANDLINE_ARGS)=(.*)$') {{ $settings[$matches[1].ToUpperInvariant()] = $matches[2].Trim() }} }} }}; $args = $settings['COMMANDLINE_ARGS']; if ($args -notmatch '(^|\\s)--skip-install(\\s|$)') {{ if ([string]::IsNullOrWhiteSpace($args)) {{ $args = '--skip-install' }} else {{ $args = $args.TrimEnd() + ' --skip-install' }} }}; $settings['COMMANDLINE_ARGS'] = $args; foreach ($name in 'PYTHON','GIT','VENV_DIR','COMMANDLINE_ARGS') {{ Write-Output ($name + '=' + $settings[$name]) }}"`) do set "%%A=%%B"

        set "PYTHON_BIN="
        if defined VENV_DIR if exist "%VENV_DIR%\\Scripts\\python.exe" set "PYTHON_BIN=%VENV_DIR%\\Scripts\\python.exe"
        if not defined PYTHON_BIN if exist "%REFORGE_ROOT%venv\\Scripts\\python.exe" set "PYTHON_BIN=%REFORGE_ROOT%venv\\Scripts\\python.exe"
        if not defined PYTHON_BIN if defined PYTHON set "PYTHON_BIN=%PYTHON%"
        if not defined PYTHON_BIN set "PYTHON_BIN=python"

        "%PYTHON_BIN%" -c "import importlib.metadata as m; from packaging.version import parse as p; import sys; versions=[d.version for d in m.distributions() if (d.metadata.get('Name') or '').lower()=='transformers']; sys.exit(0 if versions and p(versions[0]) >= p('{required_transformers_version}') else 1)"
        if errorlevel 1 (
            echo {INSTALLER_NAME}: installing transformers=={required_transformers_version}
            "%PYTHON_BIN%" -m pip install "transformers=={required_transformers_version}"
            if errorlevel 1 (
                echo {INSTALLER_NAME}: failed to install transformers=={required_transformers_version}
                pause
                exit /b 1
            )
        )

        call "%WEBUI_BAT%" %*
        endlocal
        """
    )


def write_managed_launcher(reforge_root: Path) -> Path:
    """Write the managed launcher into the host ReForge root."""

    managed_launcher_path = get_managed_launcher_path(reforge_root)
    managed_launcher_path.write_text(
        render_managed_launcher(REQUIRED_TRANSFORMERS_VERSION),
        encoding="utf-8",
        newline="\r\n",
    )
    return managed_launcher_path


def report_setup_result(
    managed_launcher_path: Path,
    transformers_upgraded: bool,
) -> None:
    """Print one concise post-install setup summary."""

    if transformers_upgraded:
        print(
            f"{INSTALLER_NAME}: upgraded transformers to {REQUIRED_TRANSFORMERS_VERSION} "
            f"and generated {managed_launcher_path.name}. Launch ReForge with that file."
        )
        return

    print(
        f"{INSTALLER_NAME}: generated {managed_launcher_path.name}. "
        "Launch ReForge with that file."
    )


def main() -> None:
    """Run extension bootstrap, host setup, and launcher generation."""

    if REQUIREMENTS_FILE.is_file():
        install_requirements(REQUIREMENTS_FILE)

    transformers_upgraded = ensure_required_transformers_version()
    reforge_root = resolve_reforge_root()
    managed_launcher_path = write_managed_launcher(reforge_root)
    report_setup_result(managed_launcher_path, transformers_upgraded)


if __name__ == "__main__":
    main()
